### PR TITLE
Adding html css and test.md files

### PR DESCRIPTION
**Pull request by orozCoding**
In this pull request I'm adding the HTML and CSS file. The Test.md file was succesfully ignored by Git.

Prove:
`The following paths are ignored by one of your .gitignore files:
test.md
hint: Use -f if you really want to add them.
hint: Turn this message off by running
hint: "git config advice.addIgnoredFile false"
`

### CODE REVIEW

**Review by VanessaAoki — CHANGES_REQUESTED** [review]
## STATUS: CHANGES REQUIRED :yellow_circle: 
Hi @orozCoding, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

### Project highlights:
- [x] Your README file looks very professional and the PR has a descriptive title/summary of the implemented changes :memo: 
- [x] Descriptive commits and correct use of the GitHub Flow :fire: 

## Required Changes ♻️
- [ ] Some of your linters checks are not passing, in order to avoid surprises like this, you should consider setting linters in your local env, so you can check in your own machine if there are any linters errors before making commits, you can read more about it [here](https://github.com/microverseinc/linters-config/tree/master/html-css).
image

#### You should also consider:
- [ ] Great job using Microverse's README template, you should consider adding a screenshot of your project to it, as well as remove any of the unused features, such as the live demo (you can always add it later, when you actually have a live demo for it).


so close

Cheers and Happy coding! 👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by orozCoding** [comment]
Thank you @VanessaAoki 

I noticed the linters checks right after submitting the pull-request review.

Now that I know what changes I need to do, I'm not sure how to proceed. 

Should I just make the changes and push them to the same branch? Or is it a different process?

**Comment by VanessaAoki** [comment]
You should make all the changes in this branch, commit them and ask for a re-review of this same pull request!

**Review by carlos-ssh — APPROVED** [review]
# 🍾🍾 **STATUS APPROVED** 👏🏽👏🏽

Hi @orozCoding , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Approved


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by orozCoding** [comment]
Thank you guys!

**Pull request merged**
